### ISSUE TITLE
"No module named 'pybea'."

### ISSUE THREAD

**Issue by tilly121212** [areed1192/python-bureau-economic-analysis-api-client#1]
Following your youtube tutorial, I cant even attempt an api request, because It's throwing a modulenotfound error.

from pybea.client import BureauEconomicAnalysisClient

**Comment by areed1192** [comment]
Did you pip install the module?

```console
pip install -e .
```

That assumes you want to do a developmental install.

**Comment by tilly121212** [comment]
Thought i did, ill try again and update.

**Comment by tilly121212** [comment]
Hey so I did pip install e .

Same error being thrown

**Comment by areed1192** [comment]
Well, if you're in VS Code, just open the terminal and then put the following command into the terminal.

```console
pip install -e .
```

It must look exactly like that command up above. Also, you need to make sure you're in the directory where the `setup.py` file is.

**Comment by tilly121212** [comment]
Well I did "pip install -e .", got successfully installed notice, also got
a "already exists" notice.

Again, I go to my tutorial.py file, with my environment active, and it
still says "ModuleNotFoundError: No module named 'pybea'"

Attempting to use your app to help me out with a school project that will
obviously make the bea api far more user friendly.

Not sure what to do to fix this error though.

thanks for your help, if you have any other ideas I'd greatly appreciate it.

**Comment by tilly121212** [comment]
Heres what my imports look like:

from pprint import pprint
from pybea.client import BureauEconomicAnalysisClient

**Comment by areed1192** [comment]
If you're using it in VS Code, make sure when your `pip installing it`, that the module is being installed to the location that you're using in VS Code. That tends to be the issue in most cases. A lot of it depends on how you setup your python environment on your system and if you have multiple installations. If you want to reach out at coding.sigma@gmail.com and we can jump on a call to walk through the issue.

**Comment by tilly121212** [comment]
I’ll try again later today and update. Thanks for the help.
